### ISSUE TITLE
Minor: parallel build aren't supported?

### ISSUE THREAD

**Issue by tommythorn** [openhwgroup/force-riscv#10]
I haven't looked into why, but it seems the build is serialized.  That's a bit painful in 2020:
```
$ make -j64
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
(to wit, `htop` makes it clear only a single process is executing at a time).

This isn't a showstopper but I'm profoundly puzzled.
[Ubuntu 20.40 LTS; some AMD64 processor]

**Comment by Leo-Wang-JL** [comment]
Thanks for spotting this issue.  We will have a fix soon.

**Comment by Leo-Wang-JL** [comment]
The latest code should have this addressed.  Please check if it work for you now.
