### ISSUE TITLE
DIFFERENCE between EVmRegimeType and EPrivilegeLevelType?

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#101]
if I want to make FORCE supporting H extension, should I need to modify EPrivilegeLevelType to H, or other value?
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/be37ad45-f7b8-46d2-a5fe-5d28aba13677)

**Comment by kong-ling-hui** [comment]
I will set regimeType according to priv.

**Comment by jjjjj-git** [comment]
how to add hypersivor in force_riscv   have you successful

**Comment by kong-ling-hui** [comment]
> how to add hypersivor in force_riscv have you successful

emm… It will waste you a lot of time, I recommend you find a ISG already support H extension.

**Comment by jjjjj-git** [comment]
Is there a code that reserves support for virtual machines in force_riscv ?or  it may be zero to do

**Comment by kong-ling-hui** [comment]
> Is there a code that reserves support for virtual machines in force_riscv ?or it may be zero to do

I think "Vm" in "EVmRegimeType" means virtual memory.

**Comment by jjjjj-git** [comment]
> > Is there a code that reserves support for virtual machines in force_riscv ?or it may be zero to do
> 
> I think "Vm" in "EVmRegimeType" means virtual memory.

so it mean force_riscv not have virtual machine.just have virtual memory

**Comment by jjjjj-git** [comment]
> > Is there a code that reserves support for virtual machines in force_riscv ?or it may be zero to do
> 
> I think "Vm" in "EVmRegimeType" means virtual memory.

Do you know the algorithm for page table conversion?，how to PTE work
