### ISSUE TITLE
how to add a new isa ext like Zba?

### ISSUE THREAD

**Issue by jjjjj-git** [openhwgroup/force-riscv#102]
first i have add a .xml in arch_data/instr   
and i assign its group ='Zba'    
second i have edit EnumsRISCV.CC and config/riscv_rv64.config and EnumsRISCV_test.cc and riscv_enum_classes.py
when i resetup .so file   have some error
how to solve it
![图片_0880c8ec0210808627](https://github.com/user-attachments/assets/b106b67c-460b-494c-9c5f-d829a47005a1)

**Comment by kong-ling-hui** [comment]
Search 'EInstructionGroupType' and 'EInstructionExtensionType', and you will find the reason. I think you can just add instructions you need in an existing xml, then genInstruction(xxx).
