### ISSUE TITLE
FORCE_CC, CC, CFLAGS and LFLAGS are non-standard 

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/force-riscv#15]
The Makefiles use `FORCE_CC` and `CC` to refer to the chose C++ compiler.  By convention `CC` is used for C compiler, and `CXX` is the C++ compiler.  It would avoid user confusion to renames as `FORCE_CXX` and `CXX` throughout.

Similarly the compile time flags should be in `CXXFLAGS`, not `CFLAGS`.  Any preprocessor flags (`-I`, `-D` mostly) should be in `CPPFLAGS`.  The linker flags should be in `LDFLAGS`, rather than `LFLAGS`.

The _make_ files work fine, so there is no hard reason to change. However using standard naming may make it easier for others to pick up the project and contribute.

HTH

**Comment by Leo-Wang-JL** [comment]
Good suggestions, thanks Jeremy

**Comment by hanfeng0114** [comment]
Stage2 work will check the possibility to chage to cmake build system, which will solve all the related problem.
@MikeOpenHWGroup please close this issue right now.

**Comment by MikeOpenHWGroup** [comment]
Thanks for the update @hanfeng0114.  Closing.
