### ISSUE TITLE
where did utils/builder/instruction/riscv/input/xxx_starter.xml come from?

### ISSUE THREAD

**Issue by ansyser** [openhwgroup/force-riscv#21]
I can't find this xxx_starter.xml in https://riscv.org/technical/specifications/  or https://github.com/riscv/riscv-isa-manual.
So where did this files come from, if we need to add new instructions?
thanks!

**Comment by Leo-Wang-JL** [comment]
If you have your own proprietary new instructions, you can add new instructions to a starter file, use the instruction builder script to process it and add new resulting instruction file inside a file in config/*.config.

**Comment by ansyser** [comment]
thanks a lot！
