### ISSUE TITLE
execute_uop() implementation

### ISSUE THREAD

**Issue by ahmedgalalramzy** [openhwgroup/force-riscv#26]
Can gmp library be used for accurate computation in this function?

**Comment by noahsherrill** [comment]
Hi Ramzy, I'm not very familiar with the gmp library, but based on a quick glance at the description, it would likely work. Most, if not all, of the operations currently referenced in Force code could probably be implemented using C++ operators, as long as attention was paid to making sure the operands were correctly signed or unsigned, and additional work was done to report condition flags, e.g. overflow. An important side note is that the execute_uop() interface was designed at a much earlier time in the project and is no longer being used. We don't have any plans to use it in the future, but you are, of course, free to experiment with it if you find it useful.

**Comment by noahsherrill** [comment]
@ahmedgalalramzy, do you have any further questions? If not, I will suggest this issue be closed.

**Comment by ahmedgalalramzy** [comment]
@noahsherrill If it is not needed in the future, then I will close the issue. Thanks
