### ISSUE TITLE
new rori instr, that added by myself refer to force_new_instr_toturial.pdf, can not run by fpix and handcar in force instr generating.

### ISSUE THREAD

**Issue by MappleM** [openhwgroup/force-riscv#31]
Hello, I try to add a new instr rori followed toturial step by step from doc/force_new_instr_toturial.pdf. But I have a problem. Now, rori instr can be generated by force correctly after I do all steps on pdf file. when I try to run ELF file using fpix/handcar, there is a error in fpix_sim.log file. It seems that modificaton to handcar have not take effect. I have added rori.cc in src, added rori.h in inc/insns, modified encoding.h file.
firstly, I added src/rori.cc file.
![image](https://user-images.githubusercontent.com/86957425/127339996-5a7d0882-85ea-4f1a-b2e0-b6154f28fd9a.png)
then, I added inc/insns/rori.h.
![image](https://user-images.githubusercontent.com/86957425/127340181-c6cdca9b-7798-4091-bbd9-e0facc215313.png)
I added some contents about RORI_MASK, RORI_MATCH and DECLEAR_INSN into encoding.h file.
![image](https://user-images.githubusercontent.com/86957425/127340500-a2093d25-940a-474d-8404-c19242c00560.png)
![image](https://user-images.githubusercontent.com/86957425/127340581-622deeeb-679b-4899-9a99-f690bb1f8f4b.png)
then I remake handcar_cosim.so and copy it to utils/handcar/
then, I added new instr into force instr-start-xml file and remake forece and fpix.
I wrote a simple template to test new rori instr.
![image](https://user-images.githubusercontent.com/86957425/127341730-067cddc4-c0c1-4ea8-aa2e-78e1972e3127.png)
as it shows in test_force.S file, rori instr was generated and its format is correctly.
![image](https://user-images.githubusercontent.com/86957425/127338587-896484a7-a393-4c14-9092-ce8cd80a3120.png)
 as show in fpix_sim.log file, rori instr can not be decode correctly, it can not be identified and trigger a illigeal instr exception.
![image](https://user-images.githubusercontent.com/86957425/127339727-61f69261-46bf-4cc0-a7ec-5d87675b0cdc.png)
tipis: rori (args unknown) 
I dont known why it error, could anyone help me? 
Please.

**Comment by noahsherrill** [comment]
I do not know the exact cause of or remedy for these issues. However, I have a couple of suggestions to try. You may need to add a line in inc/insn_list.h of the form `DEFINE_INSN(rori)`. Concerning the "args unknown" issue, I think if you add a line of the form `DEFINE_ITYPE(rori)` to src/disasm.cc, it will likely resolve it.

**Comment by MappleM** [comment]
Yes，It runs right after your guide! 
Thanks.

**Comment by MikeOpenHWGroup** [comment]
Hi @MappleM, if this problem has been resolved to your satisfaction, please close this issue.   Thanks.
