### ISSUE TITLE
do you plan to  implement sv39?

### ISSUE THREAD

**Issue by weiqi7777** [openhwgroup/force-riscv#32]
i find force-riscv don't support sv39

do you plan to implement it?

thanks
lujun

**Comment by noahsherrill** [comment]
Yes, we plan to implement support for it. However, I can't provide any timeline concerning when it will be completed.

**Comment by MikeOpenHWGroup** [comment]
Hi @weiqi7777, I will close this issue now.  Question asked and answered.

@noahsherrill, just FYI, the [CVA6](https://github.com/openhwgroup/cva6) project plans two variants that will require sv39 support.  This may be an opportunity to deploy FORCE on an OpenHW core.
