### ISSUE TITLE
Do you have a plan to support RVV 1.0?

### ISSUE THREAD

**Issue by Zissi-Lei** [openhwgroup/force-riscv#38]
Hi,
RVV 1.0 is frozen. Do you have a plan to update the tool  to support RVV 1.0?
Thanks.

**Comment by noahsherrill** [comment]
Yes, we are currently working on an update to support Version 1.0 of the vector extension. We cannot make any guarantees regarding the timeline, but currently anticipate releasing it in the first half of 2022.

**Comment by Zissi-Lei** [comment]
Thanks, I'm looking forward to this update!
