### ISSUE TITLE
How to generate correct code for Machine-mode only supported core?

### ISSUE THREAD

**Issue by MasterJerryZh** [openhwgroup/force-riscv#39]
Hi, I am using  force-riscv to verifi my cpu core in my dv env. But there are some mismatch code in generated elf file for example that csrrw satp/fcsr/stvec/scause are here. My cpu core is a Machine-mode only riscv core, and it not support U-mode or S-mode. These U/S-mode csr are not exist in my core and they will be decode as illegal instruction exception. I use this cmd "/opt64/MySoftware/force-riscv/bin/friscv -t um_itree_01_force.py" to generate elf file. Force will use default config file load from force-riscv/config/riscv_rv64.config  because I give not a valid param --cfg to it. I want know how should I do to generate correct code without any S/U-mode csr init code in the beginning for my M-mode only riscv core ? Thanks.

0000000050000000:f1402af3 CSRRS mhartid, x0, x21
0000000050000004:001009b7 LUI x19, 256
0000000050000008:033a89b3 MUL x19, x21, x19
000000005000000c:80000537 LUI x10, -524288
0000000050000010:02051513 SLLI x10, x10, 0x20
0000000050000014:02055513 SRLI x10, x10, 0x20
0000000050000018:00a98533 ADD x10, x19, x10
000000005000001c:00050067 JALR x0, x10, 0
0000000080000000:00000fb7 LUI x31, 0
0000000080000004:001f8f9b ADDIW x31, x31, 1
0000000080000008:033f9f93 SLLI x31, x31, 0x33
000000008000000c:341f8f93 ADDI x31, x31, 833
0000000080000010:00cf9f93 SLLI x31, x31, 0xc
0000000080000014:12df8f93 ADDI x31, x31, 301
0000000080000018:301f9073 CSRRW misa, x31, x0
000000008000001c:019308b7 LUI x17, 6448
0000000080000020:1fb8889b ADDIW x17, x17, 507
0000000080000024:00c89893 SLLI x17, x17, 0xc
0000000080000028:75f88893 ADDI x17, x17, 1887
000000008000002c:00e89893 SLLI x17, x17, 0xe
0000000080000030:40788893 ADDI x17, x17, 1031
0000000080000034:00d89893 SLLI x17, x17, 0xd
0000000080000038:59c88893 ADDI x17, x17, 1436
000000008000003c:30089073 CSRRW mstatus, x17, x0
0000000080000040:000a0fb7 LUI x31, 160
0000000080000044:881f8f9b ADDIW x31, x31, -1919
0000000080000048:00ef9f93 SLLI x31, x31, 0xe
000000008000004c:01df8f93 ADDI x31, x31, 29
0000000080000050:00cf9f93 SLLI x31, x31, 0xc
0000000080000054:9f9f8f93 ADDI x31, x31, -1543
0000000080000058:012f9f93 SLLI x31, x31, 0x12
000000008000005c:47ff8f93 ADDI x31, x31, 1151
**0000000080000060:180f9073 CSRRW satp, x31, x0**
0000000080000064:071cba37 LUI x20, 29131
0000000080000068:b3da0a1b ADDIW x20, x20, -1219
000000008000006c:00ca1a13 SLLI x20, x20, 0xc
0000000080000070:09ba0a13 ADDI x20, x20, 155
0000000080000074:00ca1a13 SLLI x20, x20, 0xc
0000000080000078:e63a0a13 ADDI x20, x20, -413
000000008000007c:00ca1a13 SLLI x20, x20, 0xc
0000000080000080:b00a0a13 ADDI x20, x20, -1280
**0000000080000084:003a1073 CSRRW fcsr, x20, x0**

**Comment by noahsherrill** [comment]
Unfortunately, we don't have support for generating for an M-mode only core at this time. If you are willing to modify the source code, you could try modifying `riscv/src/InitialSetupRISCV.cc` to remove references to the registers not supported by the M-mode only core. Lines such as `mpGenerator->InitializeRegisterFields("satp", field_map)` would need to be removed to avoid initializing these registers.

You might also need to make sure the register_file tags in the config file being used only reference files with registers that are legal for your design, but that may not be strictly necessary.

**Comment by MasterJerryZh** [comment]
Thanks. I will try to midify it according your guiding.
