### ISSUE TITLE
Update the README to indicate support for Vector 1.0

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/force-riscv#43]
It is my understanding that as of `114d720`, FORCE-RISCV support V1.0 of the RISC-V vector ISA.  This is a *big deal* deserving of recognition.   At a minimum, please update the README as appropriate.

**Comment by MikeOpenHWGroup** [comment]
Thanks @noahsherrill

**Comment by quswar-abid** [comment]
I think there might be few places where this update should be made. For example, [Wiki](https://github.com/openhwgroup/force-riscv/wiki#:~:text=Supports%20Vector%20extension%20V0.9.) etc.
