### ISSUE TITLE
Address table overlaps test instructions when generating with very tight memory bounds

### ISSUE THREAD

**Issue by noahsherrill** [openhwgroup/force-riscv#44]
When creating a series of tests that need to fit in a pretty reduced memory range, the address table may overlap with the code section, which has branches (it has loops and condition checking) that are sometimes messed up due to this memory being reserved for the address table. The address table appears to always be generated with a random base address. Is there a good way to determine the address at which the address table is generated or is there a good way to force the generator to use a set memory location for the address table?

**Comment by noahsherrill** [comment]
@Wlgen, I created this issue on your behalf, so I could respond to your second question mentioned in #42. I paraphrased and summarized as best I could, but please feel free to add or correct anything here.

**Comment by noahsherrill** [comment]
Unfortunately, there is no way that I know of to query the address table address range. I have a couple of suggestions for how it might be controlled, but I can't promise they will work. One approach would be to adjust the `System Physical Address Range` in `arch_data/general/variables_<arch>.xml`. This should constrain the address range for the address table, but will also have ramifications for the permitted addresses for the rest of the test generation as well.

Alternatively, if you are willing to modify the source code, the `min_ps_constr` constructed on Line 101 of `AddressTableManagerRISCV.cc` could be constructed with whatever minimum and maximum values are desired, e.g. `ConstraintSet min_ps_constr(0x0, 0x1000);`.

**Comment by Wlgen** [comment]
Hi, thanks for the answer! In the end I've made a combination of both solutions, I've created a new variable in the xml file to adjust the range in the `ContraintSet` object, that way I have a bit more flexibility if I have to change anything I can do so without compiling. I've done something similar to change the range for the exception stack, so I've been able to fix a few things thanks to this.

I guess now this issue can be closed, since everything is solved.

Thank you very much!

**Comment by noahsherrill** [comment]
That sounds like a pretty good solution using a new XML variable to control it. Would you be willing to share the changes you made with a pull request if you have time? I think others might find this to be a useful addition as well.

**Comment by Wlgen** [comment]
Of course I wouldn't mind, I'll open a pull request with these changes as soon as I can. Thanks for the proposition!

**Comment by noahsherrill** [comment]
Resolved by #51.

**Comment by jjjjj-git** [comment]
> Hi, thanks for the answer! In the end I've made a combination of both solutions, I've created a new variable in the xml file to adjust the range in the `ContraintSet` object, that way I have a bit more flexibility if I have to change anything I can do so without compiling. I've done something similar to change the range for the exception stack, so I've been able to fix a few things thanks to this.
> 
> I guess now this issue can be closed, since everything is solved.
> 
> Thank you very much!

hello,could you tell me how to edit?   Thanks very much
