### ISSUE TITLE
Parameters used to call genSFENCE seem to be not right

### ISSUE THREAD

**Issue by niuqiang-real** [openhwgroup/force-riscv#47]
Hi there,

Here is the problem: 
     Function(genFence) is used to issue sfence.vma instruction,  here is its definition:
      
    
![image](https://user-images.githubusercontent.com/99661322/153873057-fea0737b-1c21-4226-80c5-2aad0a9a0dce.png)

   One of the parameter is pte_value_reg_index, which I believe is the register to hold the value of pte.  But when it comes to the function call:
    
![image](https://user-images.githubusercontent.com/99661322/153873221-a59204ac-f380-4a64-b83f-1caeb014df23.png)

   Here I believe pte_level_reg_index is the register to hold pte level, the  parameters seem not to match. Is this a bug or some part of my understanding is not right?

   Thanks

**Comment by noahsherrill** [comment]
Your understanding is correct. This is a bug; thank you for reporting it. I will look into it further.

**Comment by MikeOpenHWGroup** [comment]
Hi @niuqiang-real, thanks for reporting the bug!   Let's keep this issue open until @noahsherrill has had a chance to fix it.

**Comment by niuqiang-real** [comment]
Hi, thanks for your reply.  It is better to close this issue after bug fix~

**Comment by niuqiang-real** [comment]
Hi, please check whether this part of code is correct or not:
     
![image](https://user-images.githubusercontent.com/99661322/155294876-cce85b8e-48f1-4607-9b1d-1d656a7e339e.png)

Here, I think there are two mistakes:

The first one is at L271: data pushed into data block should be data_block_addr_reg_val;
The second one is at L269: it should be "action_code_reg_val" instead of "result.mTargetAddr".

And why do we put current address of the AddressTable into data block? I don't really understand what AddressTable is used for.  I would appreciate it if you can help me.

**Comment by MikeOpenHWGroup** [comment]
Hi @niuqiang-real, is your latest question about "action_code_reg_val" related to this issue?   If it is, that is OK, but if it is not, please open a new issue to discuss it.  It can create confusion if we are discussing multiple different problems in one GitHub issue.

**Comment by niuqiang-real** [comment]
> Hi @niuqiang-real, is your latest question about "action_code_reg_val" related to this issue? If it is, that is OK, but if it is not, please open a new issue to discuss it. It can create confusion if we are discussing multiple different problems in one GitHub issue.

Ok, I will open a new issue~

**Comment by MikeOpenHWGroup** [comment]
Thanks @niuqiang-real!  Your support of FORCE-RISCV is greatly appreciated.

**Comment by noahsherrill** [comment]
The effect of this issue is that the page fault handlers pass the wrong ASID value to the `SFENCE.VMA` instruction when the mapping is global. @niuqiang-real is correct that the intent here is to pass the register containing the PTE value to the `genSFENCE()` method rather than the register containing the page table level. I will submit a fix for this soon.
