### ISSUE TITLE
IDE for development

### ISSUE THREAD

**Issue by KevinK-byte** [openhwgroup/force-riscv#67]
Currently attempting to use Force and hopefully in the future, able to contribute to it after understanding how it works, but I'm unsure as to how to start developing on it.

Right now I'm using visual studio code for debugging, but I can't clearly see the flow of the code since visual studio code cant break into python code and pybind library.

May I know what kind of IDE you guys are using so as to be able to break into both c++ and python code to fully debug Force?

**Comment by hanfeng0114** [comment]
Vscode is a good choice, though current Makefile based build system can't be well supprted.
We (Alibaba Xuantie team) have changed the build system to cmake, which is expected to opensourced later.

**Comment by hanfeng0114** [comment]
@KevinK-byte can we close this issue?

**Comment by hanfeng0114** [comment]
@MikeOpenHWGroup please close this issue. Stage 2 will check to change build system which is more friendly for third party IDE tools like vscode or clion.

**Comment by KevinK-byte** [comment]
> Vscode is a good choice, though current Makefile based build system can't be well supprted. We (Alibaba Xuantie team) have changed the build system to cmake, which is expected to opensourced later.

Do you mean after your new changes, we would be able to break from C++ code into python code within single vscode debug session?

**Comment by hanfeng0114** [comment]
No. 

If u want to just debug force-riscv, different IDE has differnet way. Say, vscode can support python/C++ mix debug project with DebugPy project, which allows u to launch a python process to attch the force front-end process.

Cmake system just can make IDE with better auto-complete or code reference features.

**Comment by MikeOpenHWGroup** [comment]
Closing this issue upon @hanfeng0114's recommendation.
