### ISSUE TITLE
No "usage.h" in the compilation

### ISSUE THREAD

**Issue by baichen318** [openhwgroup/force-riscv#74]
Hi all,

I follow the `Setup` manual to compile the binary `fpix` and `riscv`. I.e., I execute `./setup` in my Linux server.
However, I encountered an error that said no `usage.h` is found in `fpix/src/load_program_options.cc`.

Enclosed, please find my screenshot.
It seems that the file `usage.h` is missing in the project, which causes the error.

<img width="961" alt="Screenshot 2023-06-15 at 11 01 51 PM" src="https://github.com/openhwgroup/force-riscv/assets/33573154/09550655-572a-4842-b793-3641a8bdda74">

My Linux server is CentOS 7.9.2009 with g++ 9.2.0 and Python 3.8

Thank you in advance.

Best regards,
Chen

**Comment by baichen318** [comment]
Hi all,

**Comment by hanfeng0114** [comment]
./setup is not enough.
Please follow the wiki: https://github.com/openhwgroup/force-riscv/wiki
It seems some environment variables were not set correctly.

**Comment by hanfeng0114** [comment]
Welcom to join openhw FORCE-RISCV VTG if desired.
Follow the steps to reigister eclipse account and join openhw mattermost:
https://www.openhwgroup.org/register/
https://mattermost.openhwgroup.org/all-users/channels/vtg-force-riscv#

**Comment by baichen318** [comment]
> Welcom to join openhw FORCE-RISCV VTG if desired. Follow the steps to reigister eclipse account and join openhw mattermost: https://www.openhwgroup.org/register/ https://mattermost.openhwgroup.org/all-users/channels/vtg-force-riscv#

Thanks for your advice.

After I follow the "wiki" document and start to compile the project by executing the command in my Linux machine: `make |& tee make.log`, an error occurs.
Enclosed, please find the detailed information.

<img width="1917" alt="error" src="https://github.com/openhwgroup/force-riscv/assets/33573154/b55af2f8-3567-4e95-b139-9d33b28e88e7">

The error suggests the definition of the variable `fpixUsage` is missing (relates to "usage.h"?)

Thank you very much.

Best regards,
Chen

**Comment by hanfeng0114** [comment]
It is strange for your scenario.
usage.h is generated by file fpix/riscv/Makefile:
![image](https://github.com/openhwgroup/force-riscv/assets/8148403/70e32471-f733-4cb8-be12-dec583ddd800)
U can try the command above to see whether usage.h is not generated.

**Comment by baichen318** [comment]
> It is strange for your scenario. usage.h is generated by file fpix/riscv/Makefile: ![image](https://user-images.githubusercontent.com/8148403/246358765-70e32471-f733-4cb8-be12-dec583ddd800.png) U can try the command above to see whether usage.h is not generated.

Hi @hanfeng0114,

Thanks for your advice.

Now I can compile the binaries and generate test patterns for RV32 & RV64 automatically with the tool.

The error is due to the different line endings. In the project, all Python scripts end with CRLF, failing in executing these scripts in Linux platforms since we treat all CRLF to LF.

The error leads to failure in generating "usage.h". And compilation terminates correspondingly.

Best regards,
Chen

**Comment by sunshine-mh** [comment]
usage.h请问是怎么解决的？
