### ISSUE TITLE
Exponential increase in generation time

### ISSUE THREAD

**Issue by KevinKBytes** [openhwgroup/force-riscv#78]
Hi,

Currently using Force and I see that with an increase in the number of instructions generated, the generation time increases exponentially, something along the lines of generating 100K instruction test requires 3x time more compared to 50K instruction test. 

Has there been any code performance benchmark done to figure out which parts of the code base could possibly cause this exponential increase? Or are there any possible optimizations for Force already available or in the works?

**Comment by hanfeng0114** [comment]
I tried similar test before. And it is true the generation time increases  a lot when instruction number increases. But I doubt whether it is exponentially increasing. We made some test, actually it is nearly linear increasing, but not exactly (actually template content matters)

I didn't make detailed performance evaluation right now.
Intuitively, many data structures (constraint solver, memory model, dynamic execution generation recursive number on iss .etc.) will slow down when instruction number increases. So it will not linerar increasing.

Maybe it is lsu/mp scenarios that really matters for the performance problem.
And force-riscv is expected to run on simulation phase. We can try on emulation phase, but maybe it is not the expected place for an dynamic instruction sequencer (maybe u can try noiss mode).

So for simulation, 20 minutes' simulation time can be a good choice. 
It may run (1000 instruction/s x 60s x 20=1_200_000 instructions). 
On my machine, it costs nearly 5 minutes. 
Actually it depends on your machine and the machine state. Also the template content matters too.
It is acceptable for us.

**Comment by hanfeng0114** [comment]
Follow the steps to reigister eclipse account and join openhw mattermost:
https://www.openhwgroup.org/register/
https://mattermost.openhwgroup.org/all-users/channels/vtg-force-riscv#

Please join mattermost, we can chat there more timely.

**Comment by hanfeng0114** [comment]
Join the mattermost channel. Maybe we can make furture discussion about your scenario.
Actually performance really matters for the furture usage.

**Comment by hanfeng0114** [comment]
Add more info, virtual memory support matters a lot.

**Comment by hanfeng0114** [comment]
Any more question about this issue?
@KevinK-byte

**Comment by KevinKBytes** [comment]
No for now, will revisit this topic on mattermost at a later time.
