### ISSUE TITLE
[fail]Front-end error reported: RuntimeError: Error code: 4

### ISSUE THREAD

**Issue by superbchetan** [openhwgroup/force-riscv#79]
Hi,

If I change the vector length to 256 and element length to 32 in the `config/riscv_rv32.config` and `fpix/config/riscv_rv32.config` and run `$FORCE_PATH/utils/regression/master_run.py -f $FORCE_PATH/tests/riscv/_rv32_fctrl.py -c $FORCE_PATH/utils/regression/config/_riscv_rv32_fcfg.py -k all` 

Changes:

```
diff --git a/config/riscv_rv32.config b/config/riscv_rv32.config
index 04de69f..51740af 100644
--- a/config/riscv_rv32.config
+++ b/config/riscv_rv32.config
@@ -25,8 +25,8 @@
-    <limit name="MaxPhysicalVectorLen" value = "512"/>
-    <limit name="MaxVectorElementWidth" value = "64"/>
+    <limit name="MaxPhysicalVectorLen" value = "256"/>
+    <limit name="MaxVectorElementWidth" value = "32"/>
diff --git a/fpix/config/riscv_rv32.config b/fpix/config/riscv_rv32.config
index 6aba443..1e7dc91 100644
--- a/fpix/config/riscv_rv32.config
+++ b/fpix/config/riscv_rv32.config
@@ -23,8 +23,8 @@
-    <option name="vlen" default_value="512" description="vector register length in bits"/>
-    <option name="elen" default_value="64" description="maximum vector element width in bits"/>
+    <option name="vlen" default_value="256" description="vector register length in bits"/>
+    <option name="elen" default_value="32" description="maximum vector element width in bits"/>
```

I am getting following results:
```
Generate    : 136
Generate Fails:  27
Generate Success Rate : 80.15%

ISS Sim   : 107
ISS Sim Fails:   0
ISS Sim Success Rate : 100.00%

Total Instructions Emulated: 59502

Total Tasks     : 136
Task Fails      :  27
Task Success Rate: 80.15%

Total Run Time: 9.95404 Seconds

####
#### Reached max fails limit before test was completed.
####
Test Completed ....
```

All the 27 generate fails are pointing similar failure signature, example error message as follow:

```
[fail]Front-end error reported: RuntimeError: Error code: 4, Problems writing simulator register. CPU ID: 0, register: 'v28_4', value: 0x4c099e6aa4c17f0d, mask: 0xffffffffffffffff

  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThreadExecutor.py", line 62, in executeGenThread
    aGenThread.generate()
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 151, in generate
    seq.run()
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 49, in run
    self.generate(**kargs)
  File "/data/shared/hcg/users/udchetan/force-riscv-7-18/force-riscv/tests/riscv/instructions/v_instructions/T10-Group4_force.py", line 19, in generate
    self.genInstruction(instr, {"NoSkip":1})
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 97, in genInstruction
    return self.genThread.genInstruction(instr_name, kargs)
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 181, in genInstruction
    return self.interface.genInstruction(self.genThreadID, instr_name, kargs)

[FAIL]{front-end-error-reported} in file '../base/inc/py_modules/PyLog.h' line 58 func 'operator()'.
```

Has anyone faced the similar issue? Am I missing any configuration settings here? Any thoughts/comments would be highly appreciated. Thanks.

**Comment by superbchetan** [comment]
For standalone vector test run also hitting same error:
**command:** `./bin/friscv -t tests/riscv/vector/vector_extension_instructions_force.py --cfg config/riscv_rv32.config`

**error:** 
```
[SimApiHANDCAR::WriteRegister] v0_3 0xe870ff38f1c8c8b/0xffffffffffffffff
[SimApiHANDCAR::WriteRegister] v0_4 0xd254bb6aaf449645/0xffffffffffffffff
[fail]Front-end error reported: RuntimeError: Error code: 4, Problems writing simulator register. CPU ID: 0, register: 'v0_4', value: 0xd254bb6aaf449645, mask: 0xffffffffffffffff

  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThreadExecutor.py", line 62, in executeGenThread
    aGenThread.generate()
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 151, in generate
    seq.run()
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 49, in run
    self.generate(**kargs)
  File "/data/shared/hcg/users/udchetan/force-riscv-7-18/force-riscv/tests/riscv/vector/VectorTestSequence.py", line 52, in generate
    instr_id = self.genInstruction(instr, instr_params)
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 97, in genInstruction
    return self.genThread.genInstruction(instr_name, kargs)
  File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 181, in genInstruction
    return self.interface.genInstruction(self.genThreadID, instr_name, kargs)

[FAIL]{front-end-error-reported} in file '../base/inc/py_modules/PyLog.h' line 58 func 'operator()'.
```

**Comment by LingHua209134** [comment]
> For standalone vector test run also hitting same error: **command:** `./bin/friscv -t tests/riscv/vector/vector_extension_instructions_force.py --cfg config/riscv_rv32.config`
> 
> **error:**
> 
> ```
> [SimApiHANDCAR::WriteRegister] v0_3 0xe870ff38f1c8c8b/0xffffffffffffffff
> [SimApiHANDCAR::WriteRegister] v0_4 0xd254bb6aaf449645/0xffffffffffffffff
> [fail]Front-end error reported: RuntimeError: Error code: 4, Problems writing simulator register. CPU ID: 0, register: 'v0_4', value: 0xd254bb6aaf449645, mask: 0xffffffffffffffff
> 
>   File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThreadExecutor.py", line 62, in executeGenThread
>     aGenThread.generate()
>   File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 151, in generate
>     seq.run()
>   File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 49, in run
>     self.generate(**kargs)
>   File "/data/shared/hcg/users/udchetan/force-riscv-7-18/force-riscv/tests/riscv/vector/VectorTestSequence.py", line 52, in generate
>     instr_id = self.genInstruction(instr, instr_params)
>   File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/Sequence.py", line 97, in genInstruction
>     return self.genThread.genInstruction(instr_name, kargs)
>   File "/data/shared/mulberry/users/udchetan/force-riscv-7-18/force-riscv/py/base/GenThread.py", line 181, in genInstruction
>     return self.interface.genInstruction(self.genThreadID, instr_name, kargs)
> 
> [FAIL]{front-end-error-reported} in file '../base/inc/py_modules/PyLog.h' line 58 func 'operator()'.
> ```

Hi, 

In the test _tests/riscv/vector/vector_extension_instructions_force.py_, "VSEXT.VF8##RISCV" and "VZEXT.VF8##RISCV" are specified in the instruction list and vsew is set to 0x3 (means sew is 64). However, they are all reserved when elen is set to 32. I think you can make an adaptation and have another try.
```
    def __init__(self, aGenThread, aName=None):
        super().__init__(aGenThread, aName)

        self._mInstrList = (
            "VSEXT.VF2##RISCV",
            "VSEXT.VF4##RISCV",
            "VSEXT.VF8##RISCV",
            "VZEXT.VF2##RISCV",
            "VZEXT.VF4##RISCV",
            "VZEXT.VF8##RISCV",
        )

    # Set up the environment prior to generating the test instructions.
    def _setUpTest(self):
        choices_mod = ChoicesModifier(self.genThread)

        choice_weights = {
            "0x0": 0,
            "0x1": 0,
            "0x2": 0,
            "0x3": 10,
            "0x4": 0,
            "0x5": 0,
            "0x6": 0,
            "0x7": 0,
        }
        choices_mod.modifyRegisterFieldValueChoices(
            "vtype.VSEW", choice_weights
        )

        choices_mod.commitSet()
```

By the way, in later version by XuanTie, we will upgrade app_registers.xml and mark with both xlen and vlen, like _app_registers_rv32_v256.xml_ in your case.

**Comment by superbchetan** [comment]
Thank you @LingHua209134 and @hanfeng0114 for your response.

I have updated `tests/riscv/vector/vector_extension_instructions_force.py` as follows:
```
   def __init__(self, aGenThread, aName=None):
        super().__init__(aGenThread, aName)

        self._mInstrList = (
            "VSEXT.VF2##RISCV",
            "VSEXT.VF4##RISCV",
#            "VSEXT.VF8##RISCV",
            "VZEXT.VF2##RISCV",
            "VZEXT.VF4##RISCV",
#            "VZEXT.VF8##RISCV",
        )

    # Set up the environment prior to generating the test instructions.
    def _setUpTest(self):
        choices_mod = ChoicesModifier(self.genThread)

        choice_weights = {
            "0x0": 0,
            "0x1": 0,
            "0x2": 10,
            "0x3": 0,
            "0x4": 0,
            "0x5": 0,
            "0x6": 0,
            "0x7": 0,
        }
        choices_mod.modifyRegisterFieldValueChoices("vtype.VSEW", choice_weights)

        choices_mod.commitSet()
```

I am not very clear about what changes are required in the riscv/arch_data/reg/app_registers_rv32.xml to make it work. Can you please help me with this? Thanks again!

**Comment by hanfeng0114** [comment]
I didn't try MaxVectorElementWidth=32 locally.
U can try to change utils/builder/register_builder/riscv/app_registers_builder.py. Note the following line:
`    # number of sub-registers needed for vector 512-bit registers
    numberOfVecSubReg = a_vlen // 64

    # add vector registers V0-V31
    for i in range(0, 32):
        for subIndex in range(numberOfVecSubReg):
            app_register_doc.addPhysicalRegister(
                PhysicalRegister.createPhysicalRegister(
                    "v%d_%d" % (i, subIndex),
                    64,
                    i,
                    "VECREG",
                    aSubIndex=subIndex,
                )
            )

        app_register_doc.addRegister(create_vector_app_register(i, 64, a_vlen))
`

**Comment by superbchetan** [comment]
My current workspace is synced to 144fb52a99cde89e73552f88c872c05d2e90b603. Looks like there is some discrepancies in our code base. In my code base `numberOfVecSubReg = 8` and `create_vector_app_register` has 2 input args.

```
        # number of sub-registers needed for vector 512-bit registers
        numberOfVecSubReg = 8

        # add vector registers V0-V31
        for i in range(0, 32):
            for subIndex in range(numberOfVecSubReg):
                app_register_doc.addPhysicalRegister(
                    PhysicalRegister.createPhysicalRegister(
                        "v%d_%d" % (i, subIndex),
                        64,
                        i,
                        "VECREG",
                        aSubIndex=subIndex,
                    )
                )

            app_register_doc.addRegister(create_vector_app_register(i, 64))

```

**Comment by hanfeng0114** [comment]
We changed the build script. "64" matters. It is the register size.
Actually the configuration system need to be updated too.
