### ISSUE TITLE
I need help about FlatMap

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#86]
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/dda886ee-852f-42b7-af64-857b16f6e45c)
I excute this case, where the FlatMap is 1 or 0. But the VA always equals the PA.
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/0fb7c11d-0f25-4234-8467-6cf790ddfec7)

**Comment by hanfeng0114** [comment]
Do u mean FlatMap=1/0 in the _def_ctrl.py file or genVAforPA parameters?
From your context, I assume it is _def_ctrl.py option.
Please note that RISCV M mode is always direct map VA/PA (force-riscv doesn't support mstatus.MPRV=1 right now).
So if u want random virtual memory mapping, please change mode first.

**Comment by hanfeng0114** [comment]
Is there any more question about this issue?

**Comment by kong-ling-hui** [comment]
Thanks for your answer. I have switched to "S" mode by using the instruction "MRET", but I want to know did u have other methods to switch the mode. Looking forward to your guidance.

**Comment by hanfeng0114** [comment]
Please refer to tests/riscv/privilege_switch for demo test to switch priviledge.

**Comment by hanfeng0114** [comment]
Please reopen the issue if there is more question about this issue.

**Comment by jjjjj-git** [comment]
> ![image](https://private-user-images.githubusercontent.com/63539162/274189087-dda886ee-852f-42b7-af64-857b16f6e45c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTQxODgsIm5iZiI6MTcyNTU5Mzg4OCwicGF0aCI6Ii82MzUzOTE2Mi8yNzQxODkwODctZGRhODg2ZWUtODUyZi00MmI3LWFmNjQtODU3YjE2ZjZlNDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkY2JjMDFjN2FmMzY0NjQxZGU4ZmMwMWE3OWIyYWVlY2Q4MTg2ZTAyNDI3NWIyZjNkN2QxOWY2ZDY5ZjY5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foO_Hwjao_H4BLci5P138CsR_fTmRKGCtOpiRHMCqiE) I excute this case, where the FlatMap is 1 or 0. But the VA always equals the PA. ![image](https://private-user-images.githubusercontent.com/63539162/274190412-0fb7c11d-0f25-4234-8467-6cf790ddfec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTQxODgsIm5iZiI6MTcyNTU5Mzg4OCwicGF0aCI6Ii82MzUzOTE2Mi8yNzQxOTA0MTItMGZiN2MxMWQtMGYyNS00MjM0LTg0NjctNmNmNzkwZGRmZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNGZlZjAzNWQ4ZjdjMzZlMGE3MDZkYmJmNzY2NWI4NWM0OGIxMTBlZDM1NmY2ZDBkZTYwZTE5MWQ3ZTk2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I30m8bZc97Hwh7f4lxT3hXv2o_ct4odbhkI4I6T2AKs)

how to print the(Mem R......) all my log don't have this
