### ISSUE TITLE
After MRET，not the PC I wanted. HELP

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#88]
I used the following Python script to switch the privilege level to S or U mode, and then inserted the instructions to be executed after MRET. I found that the PC segment is not in 80011XXX. I have modified the PC in the boot section and the initial PC in PcConfig, hoping that the inserted PC will start at 80011000

**Comment by kong-ling-hui** [comment]
here is the Python script,

**Comment by kong-ling-hui** [comment]
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/abff262d-50af-478c-9c28-5d0284c2db6f)
the following is the MERT instruction I insert, and as the picture show the privilege level has been switched to S mode.
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/33dfaeea-f86c-4a44-84e3-d08d9b5e837b)
But the PC of instructions after MRET is not 80011XXX
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/c0be8099-971b-4fdb-aff7-c6014eba036e)

**Comment by hanfeng0114** [comment]
Force will try to random new instruction pc space after executing xret instruction, which will set new value for xepc register.
So it is not expected to execute from xret pc+4.
If u want to constraint pc area, try to modify memory.py.

**Comment by kong-ling-hui** [comment]
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/b510f347-a750-495a-989b-d5aa0e028e13)
I modified the address range, but when generating the case, it looked like it was stuck
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/edcf70d0-87cb-4d50-9b70-575c218e2478)
And could I modify the xepc register to execute from specified address?

**Comment by kong-ling-hui** [comment]
And another question, how to know "genInstruction" have this param, I didn't find "priv" or "epc" in FORCE-RISCV_User_Manual-v0.8.
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/2fb797ed-ff77-42fc-b15b-0ae516fcdcba)

**Comment by kong-ling-hui** [comment]
> ![image](https://user-images.githubusercontent.com/63539162/276907448-b510f347-a750-495a-989b-d5aa0e028e13.png) I modified the address range, but when generating the case, it looked like it was stuck ![image](https://user-images.githubusercontent.com/63539162/276907648-edcf70d0-87cb-4d50-9b70-575c218e2478.png) And could I modify the xepc register to execute from specified address?

I know the reason, that the VA generated didn't match range I specified, so it is generate new VA. And could I modify the xepc register to execute from specified address?

**Comment by hanfeng0114** [comment]
Note it is expected to include all instruction/data areas (except device areas) in memory.py. genVA/genPA/PC will randomize addresses based on the settings.

**Comment by hanfeng0114** [comment]
"epc" "priv" are not common parameters for a series of instructions. So it is not detailed in the spec.
Just follow the example.

**Comment by hanfeng0114** [comment]
Please reopen the issue if u have more questions.

**Comment by kong-ling-hui** [comment]
There are currently no issues. I appreciate your support very much.
