### ISSUE TITLE
After 'MRET', generating Privilege mode randomly

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#89]
- [ 1 ] Why randomly, the Privilege will be the value in MPP according to SPEC. 

- [ 2 ] I wrote the MPP to U and used {reseveRegister(name='mstatus', access='Write')}, but force always write the 'mstatus' randomly

![image](https://github.com/openhwgroup/force-riscv/assets/63539162/2bf18359-f6cd-4bdb-8252-fc09fb530663)
![image](https://github.com/openhwgroup/force-riscv/assets/63539162/1b907959-d0f0-4849-b006-50885e0801e5)

**Comment by kong-ling-hui** [comment]
I know how to switch specific Privilege using {genInstrution(MRET,{privXXX})}, but I want to try other methods, as mentioned above.

**Comment by hanfeng0114** [comment]
1. a default preamble sequence will be added before the expected "MRET" instruction is generated by the force-riscv backend
2. if user has predefined sequence class, try to modify the following line in the variable_rvxx.xml:
![Uploading image.png…]()

What's more, reserve register means only the reserved resource will not be randomly chosen.

So try to use "mret" sequence with parameters or use the priviledge switch functions or even state transition related APIs.

**Comment by hanfeng0114** [comment]
Close the issue.
if more question, please reopen or issue new issues.
