### ISSUE TITLE
Address Error

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#91]
I have modified PcConfig.py and memory39.py, but I encountered error massages "0x1ec5XXX address error"
<img width="1759" alt="微信图片_20231128170017" src="https://github.com/openhwgroup/force-riscv/assets/63539162/01c7b199-bb87-41d5-99bc-789cf8fc3d81">

**Comment by hanfeng0114** [comment]
Can u help to make "git diff" to get the changes? And the template and command info is also expected.

**Comment by kong-ling-hui** [comment]
I find the way to generate cases successfully, thanks
