### ISSUE TITLE
  What is the role of  default preamble sequence

### ISSUE THREAD

**Issue by jjjjj-git** [openhwgroup/force-riscv#93]
ok  Mr.zhao   What is the role of  default preamble sequence ；I just know  when the  mainseq has done,force riscv will branch to self,and trigger exception .how force riscv enter preamble sequence,and exit;

thank

**Comment by hanfeng0114** [comment]
I can't catch your main ideas. Just guess:
1.preamble sequence is just instructions sequence generated by backend before generating the instruction directed by template. like address composing
2.exit sequence is just a sequence hook for target termination. Currently a dead-loop is expected.
