### ISSUE TITLE
If I want to support H Extension, what can I need to do

### ISSUE THREAD

**Issue by kong-ling-hui** [openhwgroup/force-riscv#95]
I would like to use force-riscv to Itegrated Test for H Extension. Now, I know that I have to add some H Extension's instructions in riscv/arch_data/instr/xxx, such as HLV/HSV and so on, and add VS/VU/HS priveledge level in py/riscv/PrivilegeLevel.py. In the process generating cases, I need to add parameter "-n" to disable spike of force-riscv, if it dosen't support H Extension. And  may I ask what else I need to do, I need you help

**Comment by hanfeng0114** [comment]
It is a long story to support H Extension. Please join force-riscv mattermost first to start the discussion.

**Comment by kong-ling-hui** [comment]
thanks
