### ISSUE TITLE
fail by reinitialize memory range (base,offset,size) = (668,0,4)

### ISSUE THREAD

**Issue by jjjjj-git** [openhwgroup/force-riscv#96]
I have edit the memory.py in(0,0,20000),and edit the PCConfig start in addr in 0 not 50000.
also edit the EnvRiscv.py.when I run some case ,most of them fail by reinitialize memory range.
please help me  how to deal with it

**Comment by hanfeng0114** [comment]
It seems u want to try to reorgnize the memory map.
Please reply with the log info especially the error parts.

What's more, please note:
1.memory.py is just the memory map for force-riscv backend
2.handcar(spike integrated)'s memory map should also match with force-riscv settings

**Comment by mg39adi** [comment]
@xusq123 did you find a fix for this?
