### ISSUE TITLE
How to specify a random seed

### ISSUE THREAD

**Issue by jjjjj-git** [openhwgroup/force-riscv#97]
because i have edit some memory range    when I run regression with master run py,some case may success in one seed,but may fail in other seed.   how to specify seed in master run? in other word how to edit def_fctrl.py    ?

**Comment by kong-ling-hui** [comment]
Please add -s [your seed] that you can find in FORCE-RISCV_User_Manual.pdf, when you run the FORCE.

**Comment by hanfeng0114** [comment]
try master_run.py --help for more info about basic usage model.
